### ISSUE TITLE
Je penses qu'il y a quelques chose qu'il faut pas laisser 

### ISSUE THREAD

**Issue by Snipeur060** [Proxyfil/ZEvent2022Atlas#2]
Salut dans le dossier process et webhook tu a mis le lien du webhook en libre accès je suis pas forcément sur que c'est une bonne idée (L13)
```
request.post('https://discord.com/api/webhooks/1008810771599339620/0S4eAhKtgux6Fs55rtFisPsTwynlKW5d_T1w29c6GLE_aPkcCYNW_N5pNqy2Ly0XFL4K',{ json: { content: req.headers['content'], username: `${req.headers['author']} [${req.headers['ip']}]`, } },
```

**Comment by Proxyfil** [comment]
Bonjour,
Ceci n'était pas utilisé dans le code final pour des raisons techniques. Le Webhook était désactivé mais je vais quand même procéder à la suppression de ces fichiers inutiles pour être sûr.

Merci du retour
